@host = http://localhost:5170

GET {{host}}/api/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwZWU4ZjBhZi01MWI3LTRlODktOWI2Ni1iYTNiYmFlNjI2YjciLCJnaXZlbl9uYW1lIjoiYWRtaW4iLCJmYW1pbHlfbmFtZSI6InVzZXIiLCJqdGkiOiJiZjYyNDBkYy02ZWUxLTQxZDQtODQ1NC03NzQ2ODMyZDkxNjYiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTc0MTE3ODU2OCwiaXNzIjoic3VibWl0LXlvdXItaWRlYSIsImF1ZCI6InN1Ym1pdC15b3VyLWlkZWEifQ.l5ApgTEFYz-Drv1PoH4ge00OHvmcEq4lQl9jPe7czx0


###

GET {{host}}/api/categories/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwZWU4ZjBhZi01MWI3LTRlODktOWI2Ni1iYTNiYmFlNjI2YjciLCJnaXZlbl9uYW1lIjoiYWRtaW4iLCJmYW1pbHlfbmFtZSI6InVzZXIiLCJqdGkiOiJiZjYyNDBkYy02ZWUxLTQxZDQtODQ1NC03NzQ2ODMyZDkxNjYiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTc0MTE3ODU2OCwiaXNzIjoic3VibWl0LXlvdXItaWRlYSIsImF1ZCI6InN1Ym1pdC15b3VyLWlkZWEifQ.l5ApgTEFYz-Drv1PoH4ge00OHvmcEq4lQl9jPe7czx0
