@host = http://localhost:5170

POST {{host}}/api/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmMjVjMDVkNy1hYjEyLTRiZTMtODNhZi0xMjE5YjA4YjA5ZmMiLCJnaXZlbl9uYW1lIjoiYWJkdWxxYWRlciIsImZhbWlseV9uYW1lIjoicmFtemkiLCJqdGkiOiJjNjQwYjg3Yy1jMTY0LTQ0NWYtYmU2MC1iY2ZkN2YzZjU1MjUiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ2aXNpdHJvIiwiZXhwIjoxNzQxMDAyNDIwLCJpc3MiOiJzdWJtaXQteW91ci1pZGVhIiwiYXVkIjoic3VibWl0LXlvdXItaWRlYSJ9.3vJ1_DJyDy9__OAPjPTN6S78e3A24P3Un-379JGV9J0

{
  "name": "business"
}