@host = http://localhost:5170

POST {{host}}/api/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwZWU4ZjBhZi01MWI3LTRlODktOWI2Ni1iYTNiYmFlNjI2YjciLCJnaXZlbl9uYW1lIjoiYWRtaW4iLCJmYW1pbHlfbmFtZSI6InVzZXIiLCJqdGkiOiI3OWYyNzI2ZS02ODkyLTRlNWQtYjkzMS02YWUzNTRjNzIyYTEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTc0MTI1OTE1MywiaXNzIjoic3VibWl0LXlvdXItaWRlYSIsImF1ZCI6InN1Ym1pdC15b3VyLWlkZWEifQ.9ej3meFOkSx9H5c23ktc6MwNqmat8_RNh855EqoMrB4

{
  "name": ""
}