@host = http://localhost:5170

POST {{host}}/api/auth/register
Content-Type: application/json

{
  "firstName": "abdulqader", 
  "lastName": "ramzi",
  "email": "admin@test.com", 
  "password": "Admin123!", 
  "confirmPassword": "Admin123!" 
}