@host = http://localhost:5170

GET {{host}}/api/ideas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwZWU4ZjBhZi01MWI3LTRlODktOWI2Ni1iYTNiYmFlNjI2YjciLCJnaXZlbl9uYW1lIjoiYWRtaW4iLCJmYW1pbHlfbmFtZSI6InVzZXIiLCJqdGkiOiIyOTlkYjBhOS0xM2U0LTQ0ZjYtODdkNy1mNjI5NGU3ZTNhNGMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTc0MTE3NDQxMiwiaXNzIjoic3VibWl0LXlvdXItaWRlYSIsImF1ZCI6InN1Ym1pdC15b3VyLWlkZWEifQ.ezeZlXL93jlIwh49EuGpT-z-GOPNfsamL1VRQbVN6iM


###

GET {{host}}/api/ideas/8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwZWU4ZjBhZi01MWI3LTRlODktOWI2Ni1iYTNiYmFlNjI2YjciLCJnaXZlbl9uYW1lIjoiYWRtaW4iLCJmYW1pbHlfbmFtZSI6InVzZXIiLCJqdGkiOiIyOTlkYjBhOS0xM2U0LTQ0ZjYtODdkNy1mNjI5NGU3ZTNhNGMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTc0MTE3NDQxMiwiaXNzIjoic3VibWl0LXlvdXItaWRlYSIsImF1ZCI6InN1Ym1pdC15b3VyLWlkZWEifQ.ezeZlXL93jlIwh49EuGpT-z-GOPNfsamL1VRQbVN6iM
