@host = http://localhost:5170

GET {{host}}/api/ideas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmMjVjMDVkNy1hYjEyLTRiZTMtODNhZi0xMjE5YjA4YjA5ZmMiLCJnaXZlbl9uYW1lIjoiYWJkdWxxYWRlciIsImZhbWlseV9uYW1lIjoicmFtemkiLCJqdGkiOiJhMWI3ZTk0Zi1jNzVlLTRkNmYtYWJmZC1kYmVlMjkwMjk5YTAiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ2aXNpdHJvIiwiZXhwIjoxNzQxMDMyNzIxLCJpc3MiOiJzdWJtaXQteW91ci1pZGVhIiwiYXVkIjoic3VibWl0LXlvdXItaWRlYSJ9.OVZjZOq-zzDiy9TH3w1lVtV8jomCXq3JQ6HAj0MlcO0


###

GET {{host}}/api/ideas/8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmMjVjMDVkNy1hYjEyLTRiZTMtODNhZi0xMjE5YjA4YjA5ZmMiLCJnaXZlbl9uYW1lIjoiYWJkdWxxYWRlciIsImZhbWlseV9uYW1lIjoicmFtemkiLCJqdGkiOiJmM2FiZWVkOS0yOGQ3LTRiYTktYjY0OC1jOGQ4N2I3OTFhNDAiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTc0MTA3Nzk2NiwiaXNzIjoic3VibWl0LXlvdXItaWRlYSIsImF1ZCI6InN1Ym1pdC15b3VyLWlkZWEifQ.INGNDNdxTgfJf14tor-uMuBlXWByM87PnB53hrML_jg
