@host = http://localhost:5170

POST {{host}}/api/ideas/approve/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmMjVjMDVkNy1hYjEyLTRiZTMtODNhZi0xMjE5YjA4YjA5ZmMiLCJnaXZlbl9uYW1lIjoiYWJkdWxxYWRlciIsImZhbWlseV9uYW1lIjoicmFtemkiLCJqdGkiOiI4MDYzZTc0Yy05ZGViLTRhMWYtYjA3YS02NjJjZWViZGIyZjciLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTc0MTAzNTgzMiwiaXNzIjoic3VibWl0LXlvdXItaWRlYSIsImF1ZCI6InN1Ym1pdC15b3VyLWlkZWEifQ.wKq5FkEzig8e5auMF00M3TSNgeucHsg_klQ5m2eMMdk

###

POST {{host}}/api/ideas/decline/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmMjVjMDVkNy1hYjEyLTRiZTMtODNhZi0xMjE5YjA4YjA5ZmMiLCJnaXZlbl9uYW1lIjoiYWJkdWxxYWRlciIsImZhbWlseV9uYW1lIjoicmFtemkiLCJqdGkiOiI4MDYzZTc0Yy05ZGViLTRhMWYtYjA3YS02NjJjZWViZGIyZjciLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTc0MTAzNTgzMiwiaXNzIjoic3VibWl0LXlvdXItaWRlYSIsImF1ZCI6InN1Ym1pdC15b3VyLWlkZWEifQ.wKq5FkEzig8e5auMF00M3TSNgeucHsg_klQ5m2eMMdk
