@host = http://localhost:5170

POST {{host}}/api/ideas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwZWU4ZjBhZi01MWI3LTRlODktOWI2Ni1iYTNiYmFlNjI2YjciLCJnaXZlbl9uYW1lIjoiYWRtaW4iLCJmYW1pbHlfbmFtZSI6InVzZXIiLCJqdGkiOiJiZDNmNzM5OS1lNzA3LTQ1MzAtYmE4Mi05NWFjNmI1Mjk1NTQiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTc0MTI2MDYwOSwiaXNzIjoic3VibWl0LXlvdXItaWRlYSIsImF1ZCI6InN1Ym1pdC15b3VyLWlkZWEifQ.ha6CEXd27zU2qgqLlQ5hvJSewvG01_fszEoVBB4fBK0

{
  "title": "Lorem",
  "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend vulputate dui, lacinia laoreet lorem efficitur at.",
  "categoryId": 2
}