@host = http://localhost:5170

PUT {{host}}/api/ideas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmMjVjMDVkNy1hYjEyLTRiZTMtODNhZi0xMjE5YjA4YjA5ZmMiLCJnaXZlbl9uYW1lIjoiYWJkdWxxYWRlciIsImZhbWlseV9uYW1lIjoicmFtemkiLCJqdGkiOiJhMWI3ZTk0Zi1jNzVlLTRkNmYtYWJmZC1kYmVlMjkwMjk5YTAiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ2aXNpdHJvIiwiZXhwIjoxNzQxMDMyNzIxLCJpc3MiOiJzdWJtaXQteW91ci1pZGVhIiwiYXVkIjoic3VibWl0LXlvdXItaWRlYSJ9.OVZjZOq-zzDiy9TH3w1lVtV8jomCXq3JQ6HAj0MlcO0

{
  "id": 2,
  "title": "okok",
  "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend vulputate dui, lacinia laoreet lorem efficitur at.",
  "categoryId": 2
}